/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BulkCreateEntry { 'imageUrl' : string, 'designCode' : string }
export interface Design {
  'id' : bigint,
  'workType' : string,
  'imageUrls' : Array<string>,
  'createdAt' : Time,
  'isBridal' : boolean,
  'category' : string,
  'isNew' : boolean,
  'designCode' : string,
  'isTrending' : boolean,
}
export interface Measurement {
  'id' : bigint,
  'blouseLength' : string,
  'bust' : string,
  'name' : string,
  'neck' : string,
  'createdAt' : Time,
  'sleeveLength' : string,
  'shoulder' : string,
  'phone' : string,
  'waist' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllDesigns' : ActorMethod<[], undefined>,
  'createDesign' : ActorMethod<
    [string, string, string, Array<string>, boolean, boolean],
    undefined
  >,
  'createDesignBulk' : ActorMethod<[Array<BulkCreateEntry>], undefined>,
  'createMeasurement' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
  'deleteDesign' : ActorMethod<[bigint], undefined>,
  'deleteMeasurement' : ActorMethod<[bigint], undefined>,
  'getAllDesigns' : ActorMethod<[], Array<Design>>,
  'getAllMeasurements' : ActorMethod<[], Array<Measurement>>,
  'getBridalDesigns' : ActorMethod<[], Array<Design>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDesign' : ActorMethod<[bigint], [] | [Design]>,
  'getDesignsByCategory' : ActorMethod<[string], Array<Design>>,
  'getMeasurement' : ActorMethod<[bigint], [] | [Measurement]>,
  'getTrendingDesigns' : ActorMethod<[], Array<Design>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBridal' : ActorMethod<[bigint, boolean], undefined>,
  'setTrending' : ActorMethod<[bigint, boolean], undefined>,
  'updateDesign' : ActorMethod<
    [bigint, string, string, string, Array<string>],
    undefined
  >,
  'updateMeasurement' : ActorMethod<
    [bigint, string, string, string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];