/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BulkCreateEntry { 'imageUrl' : string, 'category' : string }
export interface Customer {
  'id' : bigint,
  'backNeck' : string,
  'blouseLength' : string,
  'bust' : string,
  'name' : string,
  'createdAt' : Time,
  'frontNeck' : string,
  'sleeveLength' : string,
  'address' : string,
  'shoulder' : string,
  'phone' : string,
  'waist' : string,
}
export interface Design {
  'id' : bigint,
  'workType' : string,
  'imageUrls' : Array<string>,
  'createdAt' : Time,
  'isBridal' : boolean,
  'category' : string,
  'isNew' : boolean,
  'designCode' : string,
  'isTrending' : boolean,
}
export interface Measurement {
  'id' : bigint,
  'blouseLength' : string,
  'bust' : string,
  'chest' : string,
  'name' : string,
  'neck' : string,
  'createdAt' : Time,
  'sleeveLength' : string,
  'shoulder' : string,
  'notes' : string,
  'phone' : string,
  'waist' : string,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'workType' : string,
  'createdAt' : Time,
  'deliveryDate' : string,
  'orderDate' : string,
  'stitchingType' : string,
  'customerId' : bigint,
  'designCode' : string,
}
export type OrderStatus = { 'pending' : null } |
  { 'inStitching' : null } |
  { 'delivered' : null } |
  { 'ready' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearAllDesigns' : ActorMethod<[], undefined>,
  'createCustomer' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'createDesign' : ActorMethod<
    [string, string, string, Array<string>, boolean, boolean],
    undefined
  >,
  'createDesignBulk' : ActorMethod<[Array<BulkCreateEntry>], bigint>,
  'createDesignWithAutoCode' : ActorMethod<
    [string, string, Array<string>, boolean, boolean],
    string
  >,
  'createMeasurement' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'createOrder' : ActorMethod<
    [bigint, string, string, string, string, string, OrderStatus],
    undefined
  >,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteDesign' : ActorMethod<[bigint], undefined>,
  'deleteMeasurement' : ActorMethod<[bigint], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllDesigns' : ActorMethod<[], Array<Design>>,
  'getAllMeasurements' : ActorMethod<[], Array<Measurement>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAnalytics' : ActorMethod<
    [],
    {
      'pendingOrders' : bigint,
      'completedOrders' : bigint,
      'inProgressOrders' : bigint,
      'totalDesigns' : bigint,
      'totalCustomers' : bigint,
    }
  >,
  'getBridalDesigns' : ActorMethod<[], Array<Design>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], [] | [Customer]>,
  'getCustomerOrders' : ActorMethod<[bigint], Array<Order>>,
  'getDesign' : ActorMethod<[bigint], [] | [Design]>,
  'getDesignsByCategory' : ActorMethod<[string], Array<Design>>,
  'getMeasurement' : ActorMethod<[bigint], [] | [Measurement]>,
  'getNextDesignCode' : ActorMethod<[string], string>,
  'getTrendingDesigns' : ActorMethod<[], Array<Design>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBridal' : ActorMethod<[bigint, boolean], undefined>,
  'setTrending' : ActorMethod<[bigint, boolean], undefined>,
  'updateCustomer' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updateDesign' : ActorMethod<
    [bigint, string, string, string, Array<string>],
    undefined
  >,
  'updateMeasurement' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updateOrder' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];