/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BulkCreateEntry = IDL.Record({
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'inStitching' : IDL.Null,
  'delivered' : IDL.Null,
  'ready' : IDL.Null,
});
export const Time = IDL.Int;
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'backNeck' : IDL.Text,
  'blouseLength' : IDL.Text,
  'bust' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'frontNeck' : IDL.Text,
  'sleeveLength' : IDL.Text,
  'address' : IDL.Text,
  'shoulder' : IDL.Text,
  'phone' : IDL.Text,
  'waist' : IDL.Text,
});
export const Design = IDL.Record({
  'id' : IDL.Nat,
  'workType' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'createdAt' : Time,
  'isBridal' : IDL.Bool,
  'category' : IDL.Text,
  'isNew' : IDL.Bool,
  'designCode' : IDL.Text,
  'isTrending' : IDL.Bool,
});
export const Measurement = IDL.Record({
  'id' : IDL.Nat,
  'blouseLength' : IDL.Text,
  'bust' : IDL.Text,
  'name' : IDL.Text,
  'neck' : IDL.Text,
  'createdAt' : Time,
  'sleeveLength' : IDL.Text,
  'shoulder' : IDL.Text,
  'phone' : IDL.Text,
  'waist' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'workType' : IDL.Text,
  'createdAt' : Time,
  'deliveryDate' : IDL.Text,
  'customerId' : IDL.Nat,
  'designCode' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearAllDesigns' : IDL.Func([], [], []),
  'createCustomer' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createDesign' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'createDesignBulk' : IDL.Func([IDL.Vec(BulkCreateEntry)], [IDL.Nat], []),
  'createDesignWithAutoCode' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Bool, IDL.Bool],
      [IDL.Text],
      [],
    ),
  'createMeasurement' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, OrderStatus],
      [],
      [],
    ),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteDesign' : IDL.Func([IDL.Nat], [], []),
  'deleteMeasurement' : IDL.Func([IDL.Nat], [], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
  'getAllMeasurements' : IDL.Func([], [IDL.Vec(Measurement)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getBridalDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getCustomerOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
  'getDesign' : IDL.Func([IDL.Nat], [IDL.Opt(Design)], ['query']),
  'getDesignsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Design)], ['query']),
  'getMeasurement' : IDL.Func([IDL.Nat], [IDL.Opt(Measurement)], ['query']),
  'getNextDesignCode' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getTrendingDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBridal' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setTrending' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateCustomer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateDesign' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateMeasurement' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateOrder' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BulkCreateEntry = IDL.Record({
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'inStitching' : IDL.Null,
    'delivered' : IDL.Null,
    'ready' : IDL.Null,
  });
  const Time = IDL.Int;
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'backNeck' : IDL.Text,
    'blouseLength' : IDL.Text,
    'bust' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'frontNeck' : IDL.Text,
    'sleeveLength' : IDL.Text,
    'address' : IDL.Text,
    'shoulder' : IDL.Text,
    'phone' : IDL.Text,
    'waist' : IDL.Text,
  });
  const Design = IDL.Record({
    'id' : IDL.Nat,
    'workType' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'createdAt' : Time,
    'isBridal' : IDL.Bool,
    'category' : IDL.Text,
    'isNew' : IDL.Bool,
    'designCode' : IDL.Text,
    'isTrending' : IDL.Bool,
  });
  const Measurement = IDL.Record({
    'id' : IDL.Nat,
    'blouseLength' : IDL.Text,
    'bust' : IDL.Text,
    'name' : IDL.Text,
    'neck' : IDL.Text,
    'createdAt' : Time,
    'sleeveLength' : IDL.Text,
    'shoulder' : IDL.Text,
    'phone' : IDL.Text,
    'waist' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'workType' : IDL.Text,
    'createdAt' : Time,
    'deliveryDate' : IDL.Text,
    'customerId' : IDL.Nat,
    'designCode' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearAllDesigns' : IDL.Func([], [], []),
    'createCustomer' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createDesign' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'createDesignBulk' : IDL.Func([IDL.Vec(BulkCreateEntry)], [IDL.Nat], []),
    'createDesignWithAutoCode' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Bool, IDL.Bool],
        [IDL.Text],
        [],
      ),
    'createMeasurement' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, OrderStatus],
        [],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteDesign' : IDL.Func([IDL.Nat], [], []),
    'deleteMeasurement' : IDL.Func([IDL.Nat], [], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
    'getAllMeasurements' : IDL.Func([], [IDL.Vec(Measurement)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getBridalDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getCustomerOrders' : IDL.Func([IDL.Nat], [IDL.Vec(Order)], ['query']),
    'getDesign' : IDL.Func([IDL.Nat], [IDL.Opt(Design)], ['query']),
    'getDesignsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Design)], ['query']),
    'getMeasurement' : IDL.Func([IDL.Nat], [IDL.Opt(Measurement)], ['query']),
    'getNextDesignCode' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getTrendingDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBridal' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setTrending' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateCustomer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateDesign' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateMeasurement' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateOrder' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };